= Redis

https://redis.io/

https://hub.docker.com/_/redis

== Docker版

下载

 docker pull redis:5.0.5-alpine

启动

start a redis instance

 docker run --name redis -d redis:5.0.5-alpine

start with persistent storage

 docker run -v /hostpath/redis:/data --name redis -d redis:5.0.5-alpine redis-server --appendonly yes

use your own redis.conf

 docker run -v /hostpath/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf --name redis -d redis:5.0.5-alpine redis-server /usr/local/etc/redis/redis.conf

== 配置

https://redis.io/documentation

https://www.cnblogs.com/wudequn/p/8059412.html

The self documented redis.conf for Redis X.Y

 如https://raw.githubusercontent.com/antirez/redis/5.0.5/redis.conf

编辑redis.conf文件

. 注释掉bind。因为bind配置了什么ip，别人就得访问bind里面配置的ip才访问到redis服务，而127.0.0.1是本机。bind 0.0.0.0等价于 不配置bind，即注释掉bind
. protected-mode yes改为no
. 去掉requirepass的注释并修改后面的字符串为自己的密码，如ESP496z8

=== 更多配置说明

. 默认配置有

 #   save ""
 save 900 1
 save 300 10
 save 60 10000

 appendonly no
 # appendfsync always
 appendfsync everysec
 # appendfsync no

是开启了rdb，aof是关闭的。若开启了aof，一般aof更新频率高，所以优先aof还原数据库。只有aof关闭时，才会使用rdb还原数据库。

900 秒内如果至少有 1 个 key 的值变化，则保存

300 秒内如果至少有 10 个 key 的值变化，则保存

0 秒内如果至少有 10000 个 key 的值变化，则保存

只要有一个条件满足，就会执行rdb的文件保存

. 关闭rdb，或者redis-cli命令：config set save ""

 save ""
 #   save 900 1
 #   save 300 10
 #   save 60 10000

. 开启aof（防止异常断电数据未落盘），或者redis-cli命令：config set appendonly yes

 appendonly yes

若开启了aof持久化支持，appendfsync默认每秒执行一次。no：不会主动fsync，只会由操作系统在需要的时候刷新数据。always：在每次写入后执行fsync

== K8S启、停

```cmd
cd /root/Redis
kubectl create configmap redis-config --from-file=redis.conf
kubectl get configmaps redis-config -o yaml > redis-config.yml
kubectl apply -f redis.yml

cd /root/Redis
kubectl delete -f redis.yml
kubectl delete -f redis-config.yml
rm -rf /hostpath/redis
```
