= 网站

文档1 https://about.gitlab.com/getting-help/

文档2 https://docs.gitlab.com/omnibus/docker/

文档3 https://hub.docker.com/r/gitlab/gitlab-ce/

文档4 https://hub.docker.com/r/gitlab/gitlab-ee/

== 安装

docker pull gitlab/gitlab-ce:xxx

或

docker pull gitlab/gitlab-ee:xxx

== 启动

----
例1
sudo docker run --detach \
    --hostname gitlab.example.com \
    --publish 443:443 --publish 80:80 --publish 22:22 \
    --name gitlab \
    --restart always \
    --volume /srv/gitlab/config:/etc/gitlab \
    --volume /srv/gitlab/logs:/var/log/gitlab \
    --volume /srv/gitlab/data:/var/opt/gitlab \
    docker.io/gitlab/gitlab-ce:xxx

例2
docker run --detach \
    --hostname hcindy.code.com \
    --publish 30080:80 \
    --name gitlab \
    --restart always \
    --volume /srv/gitlab/config:/etc/gitlab:Z \
    --volume /srv/gitlab/logs:/var/log/gitlab:Z \
    --volume /srv/gitlab/data:/var/opt/gitlab:Z \
    docker.io/gitlab/gitlab-ce:xxx
----

== 配置

docker exec -it gitlab vi /etc/gitlab/gitlab.rb

或

docker stop gitlab

gedit /srv/gitlab/config/gitlab.rb

找到并修改成

external_url 'http://<本机IP>'

和

gitlab_rails['lfs_enabled'] = true // 大文件支持

完后再重启

docker start gitlab

== 也可以启动时配置

----
例1
docker run --detach \
    --hostname gitlab.example.com \
    --env GITLAB_OMNIBUS_CONFIG="external_url 'http://my.domain.com/'; gitlab_rails['lfs_enabled'] = true;" \
    --publish 443:443 --publish 80:80 --publish 22:22 \
    --name gitlab \
    --restart always \
    --volume /srv/gitlab/config:/etc/gitlab \
    --volume /srv/gitlab/logs:/var/log/gitlab \
    --volume /srv/gitlab/data:/var/opt/gitlab \
    gitlab/gitlab-ce:xxx

例2
docker run --detach \
    --hostname hcindy.code.com \
    --env GITLAB_OMNIBUS_CONFIG="external_url 'http://192.168.2.70/'; gitlab_rails['lfs_enabled'] = true;" \
    --publish 30080:80 \
    --name gitlab \
    --restart always \
    --volume /srv/gitlab/config:/etc/gitlab \
    --volume /srv/gitlab/logs:/var/log/gitlab \
    --volume /srv/gitlab/data:/var/opt/gitlab \
    gitlab/gitlab-ce:xxx
----

== 番外

查看日志docker logs -f gitlab

docker ps看到显示healthy才算启动完成

== 迁移

复制数据

docker stop gitlab

cd /srv

zip -r gitlab.zip gitlab

粘贴至目标

mv gitlab.zip /srv

unzip gitlab.zip

docker run 同一个镜像

docker ps和docker logs gitlab结合观察是否有异常

如果存在权限异常，尝试

docker exec -it gitlab update-permissions

docker restart gitlab

和

docker stop gitlab

chmod 2770 /srv/gitlab/data/git-data/repositories/

如果仍存在异常，仔细看docker logs gitlab日志信息

== 使用

访问配置的地址http://192.168.2.70:30080

设置root帐户密码，IE11不可设置

创建一般帐户，e-mail随意填写

使用root帐户登陆，即可创建工程

== 创建工程

输入工程名
Visibility Level可根据需求选择
Initialize repository with a README也可根据需求勾选
最后点击Create project

== 管理工程

=== 添加成员

在Settings的Members页面里通过Select members to invite选择用户并在Choose a role permission中选择权限，最后Add to project
