= Jenkins

https://jenkins.io

https://hub.docker.com/r/jenkins/jenkins

https://hub.docker.com/r/jenkins/blueocean

== 搭建离线平台

* 在线下载插件

按照官网下载并启动程序，下载插件，将plugins文件夹拷贝（*.jpi）

* 准备环境

jenkins官网下载jenkins.war

gradle官网下载gradle-<version>-<all/bin>.zip

docker仓库下载java:<version>

* 制作镜像

```Dockerfile
# docker build -t jenkins:base .
# docker run -d --name jenkins -p 48080:8080 jenkins:base
FROM java:8

WORKDIR /root

RUN mkdir -p .jenkins/plugins

ADD jenkins.war /root
ADD plugins /root/.jenkins/plugins

ENV TZ=Asia/Shanghai

CMD java -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true -jar jenkins.war --httpPort=8080
```

```Dockerfile
# docker build -t jenkins:gradle-3.5.1 .
# docker run -d --name jenkins -p 48080:8080 jenkins:gradle-3.5.1
FROM jenkins:base

ADD gradle-3.5.1.zip /root

RUN unzip gradle-3.5.1.zip && \
    rm -f gradle-3.5.1.zip && \
    chmod 755 -R gradle-3.5.1

ENV GRADLE_HOME=/root/gradle-3.5.1
ENV PATH=$PATH:$GRADLE_HOME/bin
```

* 启动jenkins

docker run -d --name jenkins -p 48080:8080 jenkins:gradle-3.5.1

docker logs jenkins

浏览器打开并输入logs看到的password

跳过插件

创建root用户

== 结合gitlab

* 搭建gitlab环境

docker仓库下载docker.io/gitlab/gitlab-ce:<version>

启动gitlab

 docker run -d --name gitlab -p 40080:80 gitlab:10.5.4

浏览器进入并创建root密码和一般用户

* 创建gitlab工程

登录root用户创建工程，并将一般用户添加进工程授予master权限

使用一般用户用户git clone下工程，并提交spring boot工程代码

* 创建jenkins工程

仅创建空工程

new item->输入名字->选择流水线->ok->save

配置SCM

首页->点击工程名字->Configure->

pipeline板块->Definition选pipeline script from scm->scm板块选git->

Repositories板块->Repository URL填写gitlab工程地址

Credentials板块->新增账户->全局凭据、用户名和密码、全局、gitlab的root账户名称、gitlab的root账户密码->选中刚创建的账户

save

处理gitlab的webhook，当gitlab执行特定（详见勾选后展开的选项和信息）操作和Comment时触发工程任务

首页->点击工程名字->Configure->

build triggers板块->勾选Build when a change is pushed to GitLab. GitLab webhook URL: <url>

save

手动启动工程任务

首页->点击工程名字->Build Now->Status

* 配置gitlab

gitlab发起webhook触发jenkins工程

root登录->首页->点击工程名字->settings->integrations->

输入jenkins build triggers板块中...pushed to GitLab...<url>的url

去掉勾Enable SSL verification

add wobhook

生成调用gitlab的认证token

root登录->首页->头像->setting->Access Tokens->

name填写root

scopes至少勾api

create personal access token->copy

* 配置jenkins

免去gitlab发起webhook的认证信息

首页->manage jenkins->configure system->gitlab板块->去掉勾Enable authentication for '/project' end-point->save

配置调用gitlab的认证token

jenkins->manage jenkins->configure system->gitlab->

connection name填写root

gitlab host url填写gitlab url

credentials板块Add->kind: gitlab api token->api token: <gitlab的认证token>->Add->选gitlab api token

Publish over SSH

首页->manage jenkins->configure system->Publish over SSH板块->

SSH Servers板块add

name填目标机器名称

hostname填目标机器ip

username填目标机器用户

Remote Directory填目标机器目标目录（建议填根目录，然后在Publish over SSH对应的ui或Jenkinsfile填真正目标路径）

advanced

勾选Use password authentication, or use a different key

Passphrase / Password填目标机器密码

save

== Jenkinsfile

声明式和脚本式流水线都是DSL语言。片段生成器http://<ip>:<port>/pipeline-syntax/

放代码工程顶级目录下

```Jenkinsfile
pipeline {
    agent any
    stages {
        stage("build") {
            steps {
                timeout(time: 5, unit: "MINUTES") {
                    retry(2) {
                        sh "gradle build --no-daemon"
                    }
                }
            }
            post {
                always {
                    echo "This will always run"
                }
                success {
                    echo "This will run only if successful"
                    archiveArtifacts artifacts: "build/libs/**/*.*", excludes: "build/libs/**/*.original", fingerprint: true, onlyIfSuccessful: true
                }
                failure {
                    echo "This will run only if failed"
                }
                unstable {
                    echo "This will run only if the run was marked as unstable"
                }
                changed {
                    echo "This will run only if the state of the Pipeline has changed"
                    echo "For example, if the Pipeline was previously failing but is now successful"
                }
            }
        }
        stage("remote stop & clean") {
            steps {
                sshPublisher(
                    failOnError: true, 
                    publishers: [
                        sshPublisherDesc(
                            configName: "server120", 
                            transfers: [
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "/opt/my-program", remoteDirectorySDF: false, removePrefix: "", sourceFiles: "stop.sh"),
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "chmod 755 /opt/my-program/stop.sh && bash /opt/my-program/stop.sh && rm -rf /opt/my-program", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "", remoteDirectorySDF: false, removePrefix: "", sourceFiles: "")
                            ], 
                            usePromotionTimestamp: false, 
                            useWorkspaceInPromotion: false, 
                            verbose: false
                        )
                    ]
                )
            }
            post {
                always {
                    echo "This will always run"
                }
                success {
                    echo "This will run only if successful"
                }
                failure {
                    echo "This will run only if failed"
                }
                unstable {
                    echo "This will run only if the run was marked as unstable"
                }
                changed {
                    echo "This will run only if the state of the Pipeline has changed"
                    echo "For example, if the Pipeline was previously failing but is now successful"
                }
            }
        }
        stage("remote deploy & start") {
            steps {
                sshPublisher(
                    failOnError: true, 
                    publishers: [
                        sshPublisherDesc(
                            configName: "server120", 
                            transfers: [
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "/opt/my-program", remoteDirectorySDF: false, removePrefix: "build/libs", sourceFiles: "build/libs/**/*.*"), 
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "/opt/my-program", remoteDirectorySDF: false, removePrefix: "", sourceFiles: "start.sh"),
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "chmod 755 /opt/my-program/start.sh && printf '\n' | bash /opt/my-program/start.sh", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "", remoteDirectorySDF: false, removePrefix: "", sourceFiles: "")
                            ], 
                            usePromotionTimestamp: false, 
                            useWorkspaceInPromotion: false, 
                            verbose: false
                        )
                    ]
                )
            }
            post {
                always {
                    echo "This will always run"
                }
                success {
                    echo "This will run only if successful"
                }
                failure {
                    echo "This will run only if failed"
                }
                unstable {
                    echo "This will run only if the run was marked as unstable"
                }
                changed {
                    echo "This will run only if the state of the Pipeline has changed"
                    echo "For example, if the Pipeline was previously failing but is now successful"
                }
            }
        }
    }
}
```

== Jenkinsfile agent docker

个人理解：上面agent any原本是在本地（宿主机或容器中）执行命令，这些命令是在该环境有支撑（安装得有对应软件）。
而agent docker就是针对本地无环境支撑但仍要执行命里需求。
原理就是将job的目录挂载进容器，再对容器执行命令。

```sh
docker run -d \
    --name jenkins \
    -p 48080:8080 \
    -v /root/jenkins/workspace:/root/.jenkins \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /usr/bin/docker:/usr/bin/docker \
    jenkins:gradle-3.5.1
```

```Jenkinsfile
pipeline {
    agent {
        docker "node:6.11.0"
    }
    stages {
        stage("build") {
            steps {
                sh "pwd"
                sh "ls"
                sh "npm --version"
                sh "node --version"
            }
        }
    }
}
```

离线技巧：对于node需要的node_modules可以手动复制到目录下（通过上面两板块定位具体位置）

== 前后实战

方案

1. 编前编后，一起部署
2. 编后编前，一起部署
3. 编前部署，编后部署
4. 编后部署，编前部署

这里采用方案1

```Jenkinsfile
pipeline {
    agent none
    stages {
        stage("build web") {
            agent {
                docker "node:6.11.0"
            }
            steps {
                sh "npm run build:prod"
            }
            post {
                always {
                    echo "This will always run"
                }
                success {
                    echo "This will run only if successful"
                    archiveArtifacts artifacts: "src/main/resources/static/**/*.*", excludes: "", fingerprint: true, onlyIfSuccessful: true
                }
                failure {
                    echo "This will run only if failed"
                }
                unstable {
                    echo "This will run only if the run was marked as unstable"
                }
                changed {
                    echo "This will run only if the state of the Pipeline has changed"
                    echo "For example, if the Pipeline was previously failing but is now successful"
                }
            }
        }
        stage("build java") {
            agent any
            steps {
                timeout(time: 5, unit: "MINUTES") {
                    retry(2) {
                        sh "gradle build --no-daemon"
                    }
                }
            }
            post {
                always {
                    echo "This will always run"
                }
                success {
                    echo "This will run only if successful"
                    archiveArtifacts artifacts: "build/libs/**/*.*", excludes: "build/libs/**/*.original", fingerprint: true, onlyIfSuccessful: true
                }
                failure {
                    echo "This will run only if failed"
                }
                unstable {
                    echo "This will run only if the run was marked as unstable"
                }
                changed {
                    echo "This will run only if the state of the Pipeline has changed"
                    echo "For example, if the Pipeline was previously failing but is now successful"
                }
            }
        }
        stage("remote stop & clean") {
            agent any
            steps {
                sshPublisher(
                    failOnError: true, 
                    publishers: [
                        sshPublisherDesc(
                            configName: "server120", 
                            transfers: [
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "/opt/my-program", remoteDirectorySDF: false, removePrefix: "", sourceFiles: "stop.sh"),
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "chmod 755 /opt/my-program/stop.sh && bash /opt/my-program/stop.sh && rm -rf /opt/my-program", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "", remoteDirectorySDF: false, removePrefix: "", sourceFiles: "")
                            ], 
                            usePromotionTimestamp: false, 
                            useWorkspaceInPromotion: false, 
                            verbose: false
                        )
                    ]
                )
            }
            post {
                always {
                    echo "This will always run"
                }
                success {
                    echo "This will run only if successful"
                }
                failure {
                    echo "This will run only if failed"
                }
                unstable {
                    echo "This will run only if the run was marked as unstable"
                }
                changed {
                    echo "This will run only if the state of the Pipeline has changed"
                    echo "For example, if the Pipeline was previously failing but is now successful"
                }
            }
        }
        stage("remote deploy & start") {
            agent any
            steps {
                sshPublisher(
                    failOnError: true, 
                    publishers: [
                        sshPublisherDesc(
                            configName: "server120", 
                            transfers: [
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "/opt/my-program", remoteDirectorySDF: false, removePrefix: "build/libs", sourceFiles: "build/libs/**/*.*"), 
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "/opt/my-program", remoteDirectorySDF: false, removePrefix: "", sourceFiles: "start.sh"),
                                sshTransfer(cleanRemote: false, excludes: "", execCommand: "chmod 755 /opt/my-program/start.sh && printf '\n' | bash /opt/my-program/start.sh", execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: "[, ]+", remoteDirectory: "", remoteDirectorySDF: false, removePrefix: "", sourceFiles: "")
                            ], 
                            usePromotionTimestamp: false, 
                            useWorkspaceInPromotion: false, 
                            verbose: false
                        )
                    ]
                )
            }
            post {
                always {
                    echo "This will always run"
                }
                success {
                    echo "This will run only if successful"
                }
                failure {
                    echo "This will run only if failed"
                }
                unstable {
                    echo "This will run only if the run was marked as unstable"
                }
                changed {
                    echo "This will run only if the state of the Pipeline has changed"
                    echo "For example, if the Pipeline was previously failing but is now successful"
                }
            }
        }
    }
}
```