= Gitlab Runner

https://docs.gitlab.com/13.6/runner/configuration/advanced-configuration.html

https://docs.gitlab.com/ee/ci/yaml/README.html

== 安装

有多种安装办法，如通过包管理软件安装、下载runner镜像、helm安装，下面采用镜像的方式

官方有说，最好用版本匹配的runner

 docker pull gitlab/gitlab-runner:v13.6.0

先执行注册命令，通过向导配置相关信息，并持久化。特别是executor的设置，关系到runner运作方式，这里仅试用docker

 docker run --rm -it -v /root/ssd/GitlabRunner/config:/etc/gitlab-runner gitlab/gitlab-runner:v13.6.0 register

配置信息参考如下

```CMD
Enter the GitLab instance URL (for example, https://gitlab.com/):
http://192.168.0.10/
Enter the registration token:
eYREGxzbj9W7dYKK3GAr
Enter a description for the runner:
[31bff6876c73]: shared runner
Enter tags for the runner (comma-separated):
shared
Registering runner... succeeded                     runner=eYREGxzb
Enter an executor: virtualbox, docker+machine, kubernetes, docker-ssh, parallels, shell, ssh, custom, docker, docker-ssh+machine:
docker
Enter the default Docker image (for example, ruby:2.6):
alpine:3.13.0
``` 

修改 /root/ssd/GitlabRunner/config 下的配置文件，添加pull_policy

```toml
  [runners.docker]
    pull_policy = "if-not-present"
```

pull_policy = "if-not-present"


正式启动runner

 docker run -d --name gitlab-runner --restart always \
     -v /root/ssd/GitlabRunner/config:/etc/gitlab-runner \
     -v /var/run/docker.sock:/var/run/docker.sock \
     gitlab/gitlab-runner:v13.6.0

== .gitlab-ci.yml

. stage 定义任务所属的阶段
. image 指定执行任务时所需要的 docker 镜像
. services 指定了执行任务时所需的依赖服务（如数据库、Docker 服务器等）
. script 定义任务所需执行的命令
. only 只有在指定分支下 commit 才会触发
. tag 指定对应 tag 的 Runner 运行
. when 表示运行该任务所需要的必要条件，如前一阶段任务全部成功。值为 manual 时表示该操作只允许手动触发
.. on_success (default) - Execute job only when all jobs in earlier stages succeed, or are considered successful because they have allow_failure: true.
.. on_failure - Execute job only when at least one job in an earlier stage fails.
.. always - Execute job regardless of the status of jobs in earlier stages.
.. manual - Execute job manually.
.. delayed - Delay the execution of a job for a specified duration. Added in GitLab 11.14.
.. never:
... With rules, don’t execute job.
... With workflow:rules, don’t run pipeline.

特殊环境变量 GIT_STRATEGY: none ，有了这个变量，在任务执行时，会跳过克隆代码的步骤

抄个有代表性的例子

```yaml
stages:
  - test
  - build
  - deploy

variables:
  IMAGE: docker.registry/name/${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}

before_script:
  - IMAGE_TAG=${IMAGE}:${CI_COMMIT_SHA:0:8}

test_all:
  image: "pymicro"
  stage: test
  services:
    - name: mysql:5.6
      alias: mysql
  veriables:
    MYSQL_DATABASE: db
    MYSQL_ROOT_PASSWORD: password
  before_script:
    - pip install -U -r requirements.txt
  script:
    - flake8 app
    - pytest tests

build_image:
  image: "docker:17.11"
  stage: build
  services:
    - name: "docker:17.12.0-ce-dind"
      alias: dockerd
  variables:
    DOCKER_HOST: tcp://dockerd:2375
  only:
    - master
  tags:
    - build
  script:
    - docker build -t ${IMAGE_TAG} -f Dockerfile .
    - docker push ${IMAGE_TAG}

deploy_production:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  only:
    - master
  when: manual
  tags:
    - deploy-production
  script:
    - kubectl set image deploy/myproject "app=${IMAGE_TAG}" --record
```


