= 使用kubeadm安装

== 参考官网和阿里云仓库加速配置安装Docker

 # Install Docker CE
 ## Set up the repository
 ### Install required packages.
 yum install yum-utils device-mapper-persistent-data lvm2 -y

 ### Add Docker repository.
 #### yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
 yum-config-manager --add-repo \
  https://download.docker.com/linux/centos/docker-ce.repo

 ## Install Docker CE.
 yum update -y && yum install docker-ce docker-ce-cli containerd.io -y

 ## Create /etc/docker directory.
 mkdir /etc/docker

 # Setup daemon.
 cat <<EOF | sudo tee /etc/docker/daemon.json
 {
   "registry-mirrors": ["https://a18sehhp.mirror.aliyuncs.com"],
   "exec-opts": ["native.cgroupdriver=systemd"],
   "log-driver": "json-file",
   "log-opts": {
     "max-size": "100m"
   },
   "storage-driver": "overlay2",
   "storage-opts": [
     "overlay2.override_kernel_check=true"
   ]
 }
 EOF

 # Create /etc/systemd/system/docker.service.d
 mkdir -p /etc/systemd/system/docker.service.d

 # Restart docker
 systemctl daemon-reload
 systemctl restart docker
 systemctl enable docker
 systemctl status docker

== 参考官网和阿里云镜像站安装k8s

 cat <<EOF > /etc/yum.repos.d/kubernetes.repo
 [kubernetes]
 name=Kubernetes
 baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
 enabled=1
 gpgcheck=1
 repo_gpgcheck=1
 gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
 EOF

 # Set SELinux in permissive mode (effectively disabling it)
 setenforce 0
 sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
 
 cat <<EOF | tee /etc/modules-load.d/k8s.conf
 br_netfilter
 EOF

 cat <<EOF | tee /etc/sysctl.d/k8s.conf
 net.bridge.bridge-nf-call-ip6tables = 1
 net.bridge.bridge-nf-call-iptables = 1
 EOF
 sysctl --system

 yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

 systemctl enable --now kubelet

== 通过dockerhub下载k8s镜像

https://hub.docker.com/u/kubeimage

 kubeadm config images list

 docker pull <name>/kube-apiserver:<version>
 docker tag <name>/kube-apiserver:<version> k8s.gcr.io/kube-apiserver:<version>
 docker rmi <name>/kube-apiserver:<version>

== 创建集群

按版本和网络插件修改初始化命令

 kubeadm init --kubernetes-version=1.20.2 \
 --apiserver-advertise-address=192.168.0.10 \
 --pod-network-cidr=10.244.0.0/16

 mkdir -p $HOME/.kube
 cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
 chown $(id -u):$(id -g) $HOME/.kube/config

 kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml

 kubectl taint nodes --all node-role.kubernetes.io/master-
 
创建一个用于本地挂载的目录

 mkdir /root/ssd/hostpath

命令行补全

 yum install -y bash-completion
 source /usr/share/bash-completion/bash_completion
 source <(kubectl completion bash)
 echo "source <(kubectl completion bash)" >> ~/.bashrc

== Ingress

这里使用Nginx，参考官方Github，找到ingress-nginx/deploy/static/provider/kind/deploy.yaml

确认里面的image和nodeSelector，并作修改后apply -f此文件

== 销毁集群

To undo what kubeadm did, you should first drain the node and make sure that the node is empty before shutting it down.
Talking to the control-plane node with the appropriate credentials, run:
 
 kubectl drain <node name> --delete-local-data --force --ignore-daemonsets
 kubectl delete node <node name>

Then, on the node being removed, reset all kubeadm installed state:

 kubeadm reset

The reset process does not reset or clean up iptables rules or IPVS tables. If you wish to reset iptables, you must do so manually:

 iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

If you want to reset the IPVS tables, you must run the following command:

 ipvsadm -C
