= Blender

== 安装

www.blender.org

建议使用压缩包版本

== 设置

* 开始界面中可以选择 简体中文
* 编辑 -> 偏好设置 -> 界面 -> 显示 -> 分辨率缩放 可以改大一点
* 编辑 -> 偏好设置 -> 界面 -> 翻译 -> 新建数据 不勾
* 编辑 -> 偏好设置 -> 界面 -> 编辑器 -> 状态栏 -> 显示 -> 场景统计数据、系统内存、显存、Blender 版本 勾上
* 编辑 -> 偏好设置 -> 输入 -> 鼠标 -> 模拟3键鼠标 勾上 （可以 alt + 鼠标左键 旋转场景，但不建议使用，因为一些快捷键会冲突且还不能解决）
* 编辑 -> 偏好设置 -> 输入 -> 键盘 -> 模拟数字键盘 没有小键盘时勾上（用主键盘的的数字键）
* 编辑 -> 偏好设置 -> 视图切换 -> 选装 & 平移 -> 围绕选择物体旋转、深度 勾上
* 编辑 -> 偏好设置 -> 保存&加载 -> 自动运行Python脚本 勾上

操作完后 偏好设置 左下角按钮 -> 保存用户设置

* 编辑 -> 偏好设置 -> 插件 -> Node: Node Wrangler 勾上
* 编辑 -> 偏好设置 -> 插件 -> Rigging: Rigfy 勾上
* 编辑 -> 偏好设置 -> 插件 -> Import-Export: Import Images as Planes 勾上
* 编辑 -> 偏好设置 -> 插件 -> Import-Export: Export Autocad DXF Format (.dxf) 勾上
* 编辑 -> 偏好设置 -> 插件 -> Add Curve: Extra Objects 勾上
* 编辑 -> 偏好设置 -> 插件 -> Add Mesh: BoltFactory 勾上
* 编辑 -> 偏好设置 -> 插件 -> Add Mesh: Extra Objects 勾上
* 编辑 -> 偏好设置 -> 插件 -> Add Mesh: A.N.T.Landscape 勾上
* 编辑 -> 偏好设置 -> 插件 -> Interface: Modifier Tools 勾上
* 编辑 -> 偏好设置 -> 插件 -> Interface: Copy Attributes Menu 勾上
* 编辑 -> 偏好设置 -> 插件 -> Mesh: LoopTools 勾上
* 编辑 -> 偏好设置 -> 插件 -> Object: Bool Tool 勾上
* 编辑 -> 偏好设置 -> 插件 -> Render: Auto Tile Size 勾上(改选项2.90.1有，3.2.2无)
* 编辑 -> 偏好设置 -> 插件 -> UV: Magic UV 勾上

操作完后 偏好设置 左下角按钮 -> 保存用户设置

== 操作

* 鼠标左键 选择物体
* shift + 鼠标左键 多选物体
* a 全选
* aa 取消全选
* 鼠标中键 旋转
* alt + 鼠标左键 旋转
* shift + 鼠标中键 平移
* shift + alt + 鼠标左键 平移
* 小键盘0 摄像机视角
* 小键盘5 正交、透视摄像机切换
* 摄像机视角时平移、旋转、推拉，摄像机默认不会跟着动，如有需求，按 N 建 -> 视图 -> 锁定摄像机到视图 勾上
* 选中活动相机物体后，ctrl + alt + 小键盘0 会把当前的观察者视角设定成为 摄像机视角
* ctrl + alt + q 四视图进入和退出
* 包括进入四视图时，用户透视中按小键盘 7 1 3 切换其它三视图，ctrl + 7、1、3 切换其它三视图的反视图；按小键盘 9 进入反视图
* 小键盘小数点，对选中的物体进入合适的视图大小。若四视图一起联动，需要 ctrl + 小数点
* 小键盘/，聚焦选中物体并屏蔽其它物体
* home 回到场景的视角
* 显示Gizmo -> 移动、旋转、缩放 勾上，会默认对选中物体可以移动、旋转、缩放
* g 移动模式，再按x、y、z是对应轴上的移动或者 shift + x、y、z进入yz、xz、xy平面的移动，再按数字按键+回车是移动距离。alt + g 回到原来的位置
* r 旋转模式，再按r是深度上的旋转，其它同理移动
* s 缩放模式，其它同理移动
* 场景属性 -> 单位 -> 长度 可以改单位
* 物体属性 -> 视图显示 -> 轴向 勾上会显示物体自身的坐标系，如果需要按照自身坐标轴移动，则按 g x x 、 g y y 、 g z z ，或者在变换坐标系中选择局部，就会优先自身的坐标轴
* shift + a 添加物体
* x 删除物体
* shift + d 复制物体
* shift + 鼠标右键 移动游标
* f12 渲染单帧
* , 变换坐标系
* . 变换轴心点
* shift + tab 吸附模式
* ctrl + j 合并物体（最后选中的物体的原点是合并后的原点）
* l 选择相邻元素（编辑模式下）
* p 分离物体（编辑模式下，且选好物体（可以面模式+用l选择相邻元素）后，按p，选中项，此时分离出来的物体原点是分离前的原点）
* shift + r 复制上一步操作
* shift + ~ 进入第一人称模式，按 w s a d q e 进行移动，额外按 shift / alt 是加速/减速移动；空格会直接到准心瞄准的物体上；右键退出
* h 隐藏（对选中的物体）
* alt + h 显示
* ctrl + p -> 物体 设定父级（多选后的最后个活动物体是父级）
* alt + p -> 清空父级 从父级脱离出来
* ctrl + m -> x y z 在对应方向镜像复制
* ctrl + t 面模式下进行三角化

=== 动画

动画三要素：物体、灯光、摄像机

* 将软件下方的关键帧面板往上拉出来
* 选中摄像机，物体属性，在数值上按 i 键，记录关键帧
* 输出属性 -> 格式 -> 帧率 （可调）
* 按帧率和时间的乘积选择结束帧数
* 调整摄像机参数，再按 i 键，记录关键帧
* 关键帧的结束点改为最后一帧的点
* 关键帧上右键 -> 插值模式 -> 线性 （可调）
* 输出属性 -> 输出 -> 路径、文件格式
* 渲染 -> 渲染动画（ctrl + f12）

=== 坐标系

* 世界
* 局部（自身）
* 法线
* 万向：物体属性 -> 变换 -> 模式（中间是旋转轴，最后个是转向轴）
* 视图：x轴是左右，y轴是上下，z轴是里外
* 自定义：假设一个物体A，复制一份，放其它位置，并且有一些变换后，选中这个物体，变换坐标系 -> 创建坐标系 -> + ，此时被复制的物体坐标系就变成了新物体的坐标系
* 游标：用途之一就是在物体作吸附的时候，作为中心点去吸附

. 物体是有原点的，如果需要移动原点，需要先在 选项 -> 变换 -> 仅影响 -> 原点 勾上，然后进入移动模式，就可以移动原点
. 选中物体，鼠标右键，设置原点，原点 -> 几何中心，就可以把原点归位

=== 吸附

3d游标作吸附的时候，确认吸附至顶点，并且吸附基准点为中心

3d游标归位：右键 -> 吸附 -> 游标->世界原点

编辑模式 -> 面模式 -> 选择面 -> shift + s -> 游标到选中项 ，此时游标就到了这个面上，然后就可以按上述操作去作吸附

如果自身的一个点吸附到另一个点，此时一个位置是存在2个点的，可以按 m ，按距离，合并成一个点

体积（音量）的吸附，可以更方便的把一个物体放进另一个物体中

=== 编辑模式

t 隐藏/显示工具栏

进入点1、线2、面3模式之一，按住shift去按其它，可以多选

1，选择一个点， ctrl + i 反选所有点

e 挤出，默认按法向量方向，再按x y z是按对应抽方向挤出，如果再按shift + x/y/z则会锁定方向。挤出后右键取消，会造成重叠面的问题，不能倒角。可以在透视模式模式下，框选点，按M，按距离，合并点。最好是用ctrl + z作取消

挤出后，可以按需勾选翻转法线，连接的几个面会被翻转法线朝向（可以在显示叠加层里的面朝向勾选显示，蓝色是正面、红色是反面）

挤出到光标工具，ctrl + 鼠标右键，直接到光标位置

alt + e 再选择什么挤出工具

对1个点，在正视图（小键盘1）下连续挤出，可以快速构建物体的轮廓。然后选择边，按a全选，挤出会得到面。再将面挤出会得到立体图形

i 内插面，加 ctrl 会有深度的联动变化，或者按 o 进行外插面。当对多个面内插时，默认是合成一个面，此时再按 i 就会变成对各个面内插。按 b 不会对边界边进行内插

点模式，选择两个点，按 j 能进行两点相连。选择N条线后，按 f 能进行面的填充

ctrl + b 边模式下的边线倒角，在倒角时用滚轮或者 s 能控制分段数；按 p 能控制内凹或者外凸（0.25一个形变区间）；如果相邻边材质不一样，默认材质编号-1会对分，可以更换这个编号作材质的选择；在面少时，可以勾选硬化法向，仅对倒角的相邻的面进行平滑；钳制重叠是防止倒角（比如多个边倒角）时，出现穿插的现象

少面数下圆滑的方法2：对物体右键，平滑着色，然后在物体数据属性的法向中勾选自动光滑，则会按法线夹角在设定度数内的进行平滑

对于缩放的物体进行倒角可能会导致不均匀，可以在缩放物体后按 ctrl + a ，全部变换，再作倒角

alt + 左键 （开启三键模拟时双击） 选择循环边

ctrl + alt + 左键 （开启三键模拟时按住ctrl+双击） 选择并排边

ctrl + r 环切，滚轮可以调整切割次数，默认只能在物体内切割，按c或者按住alt可以移出物体外；切割时，按住ctrl吸附性的切割；按住shift进行微调的切割

k 切割，完毕后按回车确认。ctrl + k 代吸附的第一刀。切割过程中，双击左键，会自动连回起点。默认不会切开整个物体，可以按 c 进行一次切开，或者去掉遮蔽几何体的勾。

切分，能切开整个物体。轴阈值能吸附切割后距离很近的点，避免出现细微的面

多边形键形，需要保证场景中存在一个任意边数的一个面，或者场景不存在任何的面或者顶点，按住 ctrl + 左键 会创建一个新的顶点；按住 shift 可以移除

多边形键形做物体拓扑：先创建一个平面，删除所有顶点，打开吸附工具并设置吸附面和背面提出，然后可以按7进入顶视图，按住 ctrl + 左键，创建一个点，在对这个点按住左键移动一下，就能吸附到物体表面上，同理创建其它3个点，再按 a 全选这4个点，按 f 补全，此时这个面就吸附在物体上了，之后在预选的边界边上按住 ctrl + 左键 就能新建三角面，再移动这个新的顶点

旋绕工具，左右两个拖动会存在正反面问题，需要用面朝向来确认，也可以操作后勾选翻转法线。

旋绕工具做转角：面模式选中要转角的面，shift + s，游标到选中项，旋绕工具切换x/y/z方向，旋绕90度，再移动下中心位置，然后就可以挤出

光滑工具对面的效果是将边缘的面改变朝向，重复次数影响的边缘的范围。同样可以作用在线上，跟面一样是将相邻面的朝向改变（两个面的法线夹角变小）

选择边，按g，再按g，进入滑移边线，是在相邻两个面上作滑移。顶点滑移，是在相邻的线上作滑移，快捷键一样，只是选择的是点。如果选择多个点，shift + v进行多点滑移

法向缩放并不能对非均匀结构进行缩放，需要用到实体修改器

推/拉工具，可以将多个点，等距离的移动，如果是用缩放则是等比例

断离区域 v ，默认会出现孔洞，可以勾选填充来解决。要断离一个面，需要按Y，再对其进行移动（G）

断离边线 alt + d ，能够对线进行挤出并位移，可以用来描轮廓

当有使用某种工具且不方便进行框选时，可以用快捷键 b 进入框选状态

点模式下选中一个点，按 ctrl + 2 会选中该点相连的线，再按 ctrl + 3 会险种线相邻的面

边模式下，选择锐边，是相邻两个面的角度大于设定的角度，就会被判定为锐边

点、先、边模式下 shfit + g 进入选择相似菜单

设置顶点组，选择多个点后，物体数据属性面板中，顶点组按 + 号，输入个名字，再点 指定 ，或者选好点后 ctrl + g ，改名字也行。当需要选择这个组的时候，点一下名字，再点 选择 按钮

点模式下，选择 -> 按特征全选 -> 松散集合元素 能将孤立的点选出来。边模式下同理能选出孤立的边

ctrl + 小键盘+/- 进行扩选或缩选

alt + 左键 双击，选择边界边

编辑模式下 ctrl + v 进入顶点的菜单。 选择两个点后按 f ，仅仅是连接点，并不会将面划分，而按 j 则会划分面。选择多个点，菜单中选择 连接顶点对 则会按选点构成轮廓。菜单中的 顶点平滑（拉普拉斯） 可能存在边界炸面的问题，若遇此问题，可以在 物体模式 ，添加 非破坏性的拉普拉斯平滑修改器 ，此时调节 Lambda系数 就不会存在问题。

形态键 的用法：前提是物体的顶点数量不要发生变化。在 物体模式 下， 物体数据属性 ， 形态键 按 + ，创建一个基本的，再按 + 创建另一个，选中另一个时，进入 编辑模式 将物体变形（如立方体通过球形化alt + shift + s变成球），回到 物体模式 ，形态键中 相对 勾去掉（绝对模式）是使用估算时刻来进行控制。相对模式 则支持局部的变化。在已变形的基础上创建新形态需要按 下箭头菜单中的混合新形状。

shift + d 复制出的物体是独立的， alt + d 复制出的物体是关联的

编辑模式，线模式，选择一条边，ctrl + h（或者通过顶点菜单中的勾挂） 勾挂到一个新物体，物体模式 下移动这个新物体就会联动之前的边所在物体变化

N个骨骼构成一个骨架，勾挂到骨骼的操作方法：可以先在 物体数据属性 中的 视图显示 下勾上 名称，这样骨架中的骨骼会显示名字。然后选择骨架，进入 编辑模式 ，选中一个骨骼，回到物体模式，选中网格，再进入编辑模式，选择勾挂的顶点，ctrl + h，选择 勾挂到选中的物体骨骼，此时就可以在网格的修改器中确认到勾挂的骨骼名称。选中骨架，进入姿态模式，调整骨骼就会有联动效果

顶点当其它物体的父级（相当于勾挂的反操作）：一个顶点或者三个顶点（三点是用的中心位置）。物体模式，选中子集物体，再选中父级物体，进编辑模式，选中顶点，ctrl + p，创建父级顶点。此时移动此顶点，另一个物体就会有联动效果

边菜单 ctrl + e 。菜单中的 桥接循环边 是比 f 更强大的边线连接创建面的工具，还可以用来打孔，比如正方体选择相对的两个面， i 进行内插面，然后再 桥接循环边 ，就会出现孔洞。菜单中的 螺旋 和旋绕是同样的创建概念，就是以 游标 为中心，基于 当前视觉 的创建，但是和旋绕不同的是需要一个 开口的基准形状。菜单中的 反细分 ，要作精确控制的话，需要选择3条或4条边，再执行 反细分 。菜单中的 顺时针/逆时针旋转边线 ，可以在不改变面数的情况下让循环方向发生变化。菜单中的 边线折痕 对应的是表面细分修改器，标记折痕后可以在 条目 下进行折痕的数值设置，或者 shfit + e 拖动鼠标控制折痕系数，之后 物体模式 在修改器中添加 表面细分修改器，此时有折痕的面不会被细分。菜单中的 倒角边权重 同折痕类似，是对应修改器中的 倒角修改器 ，但不同是有倒角权重的才会进行倒角。菜单中的 标记缝合边 ，是用来生成UV的切割边，也就是在没有UV时，选择需要标记的边，再全选（边模式），按 u ，uv展开，此时就可以在 UV编辑 窗口中看到结果。菜单中的 标记锐边 是对应平滑修改器的，被标记的不会进行平滑。菜单中的 标记freestyle边 是对应 渲染属性 下的 Freestyle ，勾上后，按 f12 会将渲染的物体渲染出边框，默认是自动的，如果需要自定义显示边框的话，就可以用这个标记

s x 0 能够将两个顶点对齐（位于某一坐标轴上下，不同坐标轴按y或z）

面菜单 ctrl + f 。菜单中的 尖分面 ，可以产生一个顶点，连接面上的各个点，然后可以向上或者向下突起。菜单中的 面三角化 就是将多边形转化成三角面，快捷键 ctrl + t。菜单中的 三角面->四边面 则是反操作，但是要受 面夹角最大值 和 最大形状角度 的阈值影响。菜单中的 面实体化 ，最好是把 面朝向 开启，因为在实体化后进行调节，可能法线方向不是想要的方向，当法线是相反时，可以选中面，按 alt + n ， 重新计算外侧 就可以校正回来。菜单中的 线框 ，勾选折痕后，在 物体模式下 加 表面细分修改器 ，才会保持原形状。菜单中的 栅格填充 可以对偶数的点进行填充，以封闭孔洞。菜单中的 完美建面 是优化三角面的。菜单下的 交集（切割） 会根据参数的不同而产生相交物体的孔洞、割线、连成一体，产生的内侧面可以在 选择 菜单中 按特征全选 ， 内侧面 ，删除。菜单中的 交集（布尔） 则会是根据交集、并集、差值进行变换。菜单中的 焊接边线到面 对于细分面多的时候可能不会出现想要的效果。菜单中的 平滑着色 是将边的法向进行平滑（可以显示边法向后观察法向夹角），同样菜单中的 平直着色 则是相反操作

一个改变布线结构的方法，进行内插面，按 s 0，合并顶点，若需要四边面，则选择一些边后按 x ，有限融并。

shfit + a ，文本，编辑模式，物体数据属性，字体，打开文字文件，选择一个中文的字体（如果要输入中文的话），然后需要用粘贴的方式进行“输入”（改变文字内容），物体模式，选中后右键，转换到网格，此时的三角面会比较混乱（编辑模式，透视模式，显示物体网格边能看到），就可以用 ctrl + f 的 完美建面 作优化。

蒙皮是给线外包上面。对线添加蒙皮修改器，ctrl + a （网格菜单 变换 重置蒙皮尺寸）就可以改变蒙皮的结果

物体属性 视图显示 纹理空间 ，打勾能看到纹理空间的大小。配合举例：给物体（平面更能看出纹理空间）新建一个材质，拖一个视窗改为 着色器编辑器 模式，拖一个图片进来当纹理，连接 颜色和基础色 。shift + a 矢量 映射 ，将新增的这个面板中的 矢量 和 图片的 矢量 相连。shift + a 输入 纹理坐标 ，将新增的这个面板中的 生成 和 映射的面板矢量 相连。再在主视图的 编辑模式 网格菜单 变换 移动/缩放纹理空间 ，滑动鼠标就能看出效果

网格菜单 镜像 下的选项，可以用 ctrl + m 后 按 x / y / z 来取代，更方便的让物体作镜像变换

选中物体中的面后按 y 后就可以独立移动这个选中面（网格），但如果选的是点或者线，虽然也可以移动出来，但原本物体上的不会消除，此时就要用 alt + m 按顶点拆分面&面/沿边拆面，此时相邻的面就可以移动了（和前面对面进行  y 拆分不是同一逻辑）

场景集合下，一个物体包含多个物体，需要分离则可以 按p 后根据实际需求分离

投影切割，切割物体（线框边界边），被切割物体，确定好视角（如果物体是有角度的，可以选中物体后 shift + 7）。选中切割物体，加选被切割物体，编辑模式，网格，投影切割，物体模式，选中被切物体，编辑模式，就能看到切割物体的轮廓了。但是不同版本操作方式可能不同，比如 选中被切割物体 ，保证有一定的细分， 确定角度， 选中切割物体（场景集合中）， 网格 投影切割

网格 清理 精简几何体，可以以塌陷的方式降低面数

要用凸面，不要用凹面，当加修改器，比如细分修改器，凹面会变得不可控。可以在 网格 清理 拆分凹面 选项下改变凹面

组: 选择物体， shift+a ， 网格 ， 绑定父级到空物体


== machin3tools 

物体原点到活动点: tab 顶点 选中点 shift+s toVert

合并到活动点: 选择n个点 ctrl+1 

合并到中心: 选择n个点 shift+1 

合并到路径（不能框选，只能点选）: 选择n个点（可以是不相邻的） alt+1。顺时针/逆时针选择4个点，会决定是横向合并还是纵向合并。另外搭配 tab 的 自动合并。合并完后如果不是想要的效果可以试下 长度 选项

点对点连接: ctrl+alt+1 选择点的逻辑和合并到路径一样

顶点滑动: 选择点 最后一个是活动项 shift+alt+1。此时其它点和活动项有一个示意的连线，点可以在这条连线上滑动（移动）

ctrl+2 在选择小于等于2个顶点时会是切刀，反之是连接顶点路径（四边面上）/连接到活动项（多边面）。选择一个边或多个边的话是旋转边，如果边是闭合的则是按边选面或按面选边（面模式下选择多个面）

shift+2 标记/清除锐边

alt+2 偏移边线并滑移。对应原生快捷键 ctrl+shift+r 选择边或面进行偏移

alt+双击边，能够选择轮廓，ctrl+3可以按轮廓补面（补洞）

在拐点ctrl+3，能够智能的补面（对于边线条件不够的时候，f是补不了的）

选择多个面，ctrl+3 可以实现复制并分离物体

ctrl+4 清理，根据据徐进一步勾选或点击选项

原生游标到活动项不会改变游标的旋转信息，m3工具可以。 shift+s toFace（不包含旋转信息按alt，只改变游标旋转按ctrl）

alt+a 对齐工具，选中物体后按快捷键，再根据需求点选按钮。另外对骨架也可以对齐，A骨架对齐到B骨架选中的骨骼根上。两个物体对接，如果有不同旋转，可以线选边，对齐后，再选点进行对齐（对接）

至少选3个顶点， alt+a ，拉直。选择顺序会影响拉直的参考线（第一个点和最后点）。如果是边模式下，多个边最后拉直的参考是两个边界的点

shift+alt+x/y/z 一键镜像，根据需求选对应的按钮，对应原生的镜像修改器。批量删的话，选中有镜像的物体，右键，machine3工具，取消镜像

ctrl+f 可以选择显示镜像部分

ctrl+s 可以快速载入 空工程时在m3工具中设置的世界环境 和 常用材质

pageup 是一个把常用功能集中面板显示的快捷键，连按两下是持续显示

pagedown 相机和视图的菜单，同上是个集合面板

n m3 智能驱动器， 上面个驱动器的值设置上下限并确定方向，下面个驱动器同理。然后先选中第一个物体，再选中第二个，再在智能驱动器上点击 驱动 ，此时移动第一个物体，第二个物体就会联动移动

n m3 unity 可以导出、三角化、恢复

shift+鼠标上/下翻页按键，是吸附/变换的集成面板

shift+c 集合菜单。清除是删掉空的集合

编辑模式下 tab 表面滑动。此时移动顶点会在面，包括有曲率的面上移动，而不会移出去。退出该模式则 tab 退出表面滑动

组: 选择物体 右键 组 群组(ctrl+g)。 相反就选择 取消群组。另外组也可以包括组。新添加物体到组的话，先选添加的物体，再选组，右键，组，添加到组。组菜单中的 组转换 ，是将原生的将物体绑定至空物体的组转换成m3的组。 在大纲视图上按 主键盘的1 ，会将大纲变成组模式（显示的选项是组空物体），退回大纲模式，则再按1

选择面数大于4，m3可以在基于面生成螺纹: 编辑模式 选中面 右键 m3 添加螺纹

alt + e ，基于游标（包含方向）进行旋绕

基于视角，ctrl + 2，就能物体投影切割

删掉物体，但数据仍然保留在blender文件中，要清除的话，ctrl+s，清理blender文件

ctrl+s 重新链接库，是对于关联进来的blender及时更行（原文件发生变化）

n m3 按压。 解决挤出非流型的问题（连续挤出时，第二层开始就会出现问题）

