= CentOS7

https://www.centos.org/

== 安装系统

. CentOS7官网，下载ISO镜像，最简是minimal，最全是everything
. 使用UltraISO将ISO镜像制作成U盘启动

TIP: 有的软件制作U盘启动后不能直接引导进入安装界面，可以在选择安装界面按tab键，改成vmlinuz initrd=initrd.img linux dd quiet并回车后查看U盘盘符，重启电脑后同样界面改成对应盘符后回车，如vmlinuz initrd=initrd.img inst.stage2=hd:/dev/sdb4 quiet

. 安装配置界面
.. 选择语言和键盘都是英文
.. 进入网络配置界面，修改局域网中不重名的hostname，如hcindy-server。点选网卡并拨开开关，将其设置为开机启动，按需设置静态IP，DNS，更改设置后需关闭再打开网卡
.. 进入时间配置界面，点选时区，确保时间准确，或者使用网络获取时间
.. 进入分区配置界面，勾选需分区的硬盘并点选手动分区，进入正式分区界面，按需划分各区，一般分区选择Device Type: Standard Partition，File System: xfs，若无法通过则参考提示调整分区
.. 按需选择安装界面和开发者库
.. 设置root密码，按需设置一般用户和勾选将其设为管理员

TIP: 如果是无线网卡，尝试拨开开关，若正常启动，则可选择连接列表，按需选择并输入密码，若无响应，尝试按下键盘上的无线网卡开关按键（快捷键）后再拨开开关，正常启动后同上操作

TIP: 如果有固态硬盘，可以考虑将其分在/home下，其余都分在机械硬盘下

== 配置

. 关闭防火墙

 service firewalld stop
 chkconfig firewalld off

. 关闭SELinux

 setenforce 0
 sed -i "s;SELINUX=.*;SELINUX=disabled;" /etc/selinux/config

. 开启/关闭ssh的root登陆

 vi /etc/ssh/sshd_config
 PermitRootLogin，将前面的#去掉/添加
 
 systemctl restart sshd
 
. 设置网卡随系统启动而启动

 vi /etc/sysconfig/network-scripts/<网卡名>
 修改或添加里面的ONBOOT为yes/no
 添加DNS1=""和DNS2=""
 
 systemctl restart network
 
. 设置电源策略

 vi /etc/systemd/logind.conf
 去掉HandlePowerKey注释
 去掉HandleLidSwitch注释并修改为ignore

 systemctl restart systemd-logind

 按电源键后关机HandlePowerKey=poweroff
 合上笔记本盖子后什么也不做HandleLidSwitch=ignore
 备选项有ignore、poweroff、reboot、halt、suspend、hibernate、hybrid-sleep、lock、kexec
 
. 设置hosts

 echo <ip> <域名> >> /etc/hosts

. 关闭swap

 swapoff -a
 sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

. 设置国内yum源

 yum install -y wget
 mkdir /etc/yum.repos.d/bak && mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak
 wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.cloud.tencent.com/repo/centos7_base.repo
 wget -O /etc/yum.repos.d/epel.repo http://mirrors.cloud.tencent.com/repo/epel-7.repo
 yum clean all && yum makecache

 yum update -y
 
== 升级内核

 rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
 rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
 yum --disablerepo="*" --enablerepo="elrepo-kernel" list available
 yum --enablerepo=elrepo-kernel install kernel-ml -y

 grub2-set-default 0
 grub2-mkconfig -o /boot/grub2/grub.cfg
 reboot

 rpm -qa | grep kernel
 yum remove -y kernel-3.10.0-xxx

== 命令

. ip

 ip a
 ip link set <网卡名> up/down
 ip link show <网卡名>
 ip addr show <网卡名>

. find

 find <path> -name <name> -type <f/d> 在指定路径下查找指定名称的文件/文件夹

. hostnamectl

 hostnamectl set-hostname <name> 修改host名称

. yum 包管理

 yum search <name> 搜索
 yum install <name> 联网安装
 yum localinstall *.rpm 本地安装
 rpm -Uvh *.rpm 本地安装
 rpm -ivh *.rpm 本地安装
 yum install <name> --downloadonly --downloaddir=<path> 只下载不安装
